Repository hmcts/lau-case-backend, pull requests merged in 2022-10, with the labels that each got.

#132 Lau 518
  audit.json
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-132

#134 LAU-526 dependency check fix
  audit.json
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-134

#135 LAU-526 Dependency Check failed
  audit.json
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-135

#133 LAU-496 Fix NPE and improve caseRef validations.
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchPostSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/CaseSearchPostHelper.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/SearchInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-133

#136 LAU-499 Socket Timeout addition
  src/main/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-136

#137 LAU-529 Tidy up all incoming caseRefs.
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/CaseRefsUtils.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLogTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLogTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-137

#138 Revert "LAU-529 Tidy up all incoming caseRefs."
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/CaseRefsUtils.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLogTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/dto/SearchLogTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifierPostExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-138

#139 LAU-531: Update socket timeout to 60 seconds.
  src/main/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-139

#140 LAU-524 Disable nightly build during weekend
  Jenkinsfile_nightly
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-140
