Repository hmcts/lau-case-backend, pull requests merged in 2022-12, with the labels that each got.

#177 Lau 570
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-177

#175 LAU-563 Upgrade Terraform version
  infrastructure/.terraform-version
Labels: ns:lau, prd:lau, keep-helm, rel:lau-case-backend-pr-175

#178 LAU-563 remove quotes
  infrastructure/variables.tf
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-178

#179 LAU-563: Fix TF Script
  infrastructure/variables.tf
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-179

#176 Lau 567
  charts/lau-case-backend/Chart.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-176

#181 LAU-572 changing dependabot config
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-181

#184 LAU-575 suppressing CVE
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-184

#183 LAU-555: Update to resolve workflow deprecated versions.
  .github/workflows/ci.yml
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-183

#188 LAU-579 dependency upgrade
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-188

#189 LAU-579 Junit upgrade
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-189
