Repository hmcts/lau-case-backend, pull requests merged in 2022-09, with the labels that each got.

#121 LAU-510 Sankeyaml dpendency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-121

#122 lau-489 Upgrade gradle to 7.5.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-122

#124 LAU-512 remove suppression
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-124

#123 LAU-385: Initial update for case deletion logging.
  README.md
  bin/create-log-and-audit-users.sh
  bin/env_variables_all.txt
  bin/idam-client-setup.sh
  bin/idam-create-caseworker.sh
  bin/idam-role-assignable.sh
  bin/idam-role.sh
  bin/idam-service-token.sh
  bin/idam-user-token.sh
  bin/set-environment-variables.sh
  build.gradle
  ccd
  compose/README.md
  compose/backend.yml
  compose/defaults.conf
  compose/frontend.yml
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/AbstractSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionDeleteSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionGetSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionPostSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchDeleteSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchGetSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchPostSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/CaseActionGetHelper.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/CaseActionPostHelper.java
  src/integrationTest/resources/application.yaml
  src/integrationTest/resources/features/get_case_action.feature
  src/integrationTest/resources/features/post_case_action.feature
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/AuthorizationAuthenticator.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/authorization/RestApiPreInvokeInterceptor.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/CaseAction.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/CaseActionConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/CommonConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/constants/ExceptionMessageConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseSearchAuditCases.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionInputParamsHolder.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/dto/ActionLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/InputParamsVerifier.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifier.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V010__Add_Delete_Case_Action.sql
  src/main/resources/h2/V001__Schema.sql
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/authorization/AuthorizationAuthenticatorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/handlers/RestApiPreInvokeDeleteInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/handlers/RestApiPreInvokeInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryStartEndTimeTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/ActionInputParamsVerifierGetExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/ActionInputParamsVerifierTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-123

#125 LAU-514 Security Scan fix
  audit.json
  compose/backend.yml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-125

#127 LAU-514 moving password to environment variable
  bin/env_variables_all.txt
  compose/backend.yml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-127

#129 LAU-520 dependency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-129

#128 LAU-518 Security Scan seperate docker
  audit.json
  security.sh
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-128

#130 LAU-518 security scan fix
  audit.json
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-130

#131 LAU-518 security scan fix
  audit.json
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-131
