Repository hmcts/lau-case-backend, pull requests merged in 2022-11, with the labels that each got.

#142 LAU-553 Dependency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-142

#143 LAU-546 Add SonarQube badges and Overview section
  README.md
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-143

#144 LAU-549 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-144

#145 Configuring Dependabot
  .github/dependabot.yml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-145

#159 LAU-556 Upgrading libraries
  build.gradle
  charts/lau-case-backend/Chart.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-159

#160 LAU-556 upgrade more libraries
  audit.json
  charts/lau-case-backend/Chart.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-160

#174 LAU-569: Postgresql update
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-174
