Repository hmcts/lau-case-backend, pull requests merged in 2022-04, with the labels that each got.

#90 LAU-366: Dependency check postgresql
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-90

#91 LAU-366: Fix vulnerability.
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-91

#92 LAU-373: Suppress vulnerability with spring-plugin.
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-92

#93 LAU-377: Suppress springfox vulnerabilities
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-93

#94 LAU-89: Security scan fix
  README.md
  build.gradle
  security.sh
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-94

#96 LAU-387: Update to fix security scan.
  security.sh
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-96
