Repository hmcts/lau-case-backend, pull requests merged in 2023-03, with the labels that each got.

#235 LAU-611 dependabot configuration
  .github/dependabot.yml
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-235

#243 Lau-618 suppress CVE-2021-1471
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-243

#250 Fix CVE-2023-28708
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-250

#251 Spring-framework-CVE-2023-20861-fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-251
