Repository hmcts/lau-case-backend, pull requests merged in 2023-06, with the labels that each got.

#292 LAU-662 return case action results in desc order
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditFindCaseRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
Labels: ns:lau, prd:lau, keep-helm, rel:lau-case-backend-pr-292

#296 LAU-668 security scan fix
  audit.json
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-296

#298 LAU-673 suppressing CVE-2023-20883
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-298

#305 LAU-681 suppress CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-305

#306 LAU-661 bump Spring Boot from 3.0.8 to 3.1.1
  build.gradle
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/security/SecurityConfiguration.java
  src/main/resources/application.properties
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-306

#307 LAU-688 bump tomcat to address CVE-2023-34981
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-307
