Repository hmcts/lau-case-backend, pull requests merged in 2023-04, with the labels that each got.

#257 Make startTime endTime mandatory search parameters for CaseSearch and…
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionDeleteSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseActionGetSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchDeleteSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CaseSearchGetSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/bdd/CommonSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/RestConstants.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/cases/helper/RestHelper.java
  src/integrationTest/resources/features/get_case_action.feature
  src/integrationTest/resources/features/get_case_search.feature
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifier.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseActionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/controllers/CaseSearchControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryStartEndTimeTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryCaseRefTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/utils/NotEmptyInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-257

#258 Remove unnecessary hikari configs
  src/main/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-258

#260 Decrease connection pool size as per hikari article - https://github.…
  src/main/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-260

#264 Update ignore cookies audit.json
  audit.json
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-264

#266 Lau 614
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/domain/CaseActionAudit.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/QueryBuilder.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/SqlCountStatementInterceptor.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V011__Add_case_action_case_jusrisdiction_index.sql
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryStartEndTimeTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseActionAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/QueryBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/helpers/SqlCountStatementInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseActionServiceTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-266

#267 Update case search query
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditFindCaseRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchService.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryCaseRefTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/repository/CaseSearchAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/service/CaseSearchServiceTest.java
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-267

#270 LAU-646 upgrade vulnerable to CVE-2023-20863 libraries
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-case-backend-pr-270
