Repository hmcts/lau-case-backend, pull requests merged in 2024-01, with the labels that each got.

#519 LAU-829 adding subnet expended for aat
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: prd:lau, ns:lau, destroy, rel:lau-case-backend-pr-519

#523 Revert renovate update to fix the master build
  build.gradle
Labels: prd:lau, ns:lau, rel:lau-case-backend-pr-523

#531 LAU-744 bump flyway to v10.5.0
  build.gradle
  charts/lau-case-backend/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayCustomConfig.java
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayMigrationStrategyConfiguration.java
  src/test/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayConfigurationTest.java
Labels: prd:lau, ns:lau, rel:lau-case-backend-pr-531

#532 Lau 744 bump flyway
  build.gradle
Labels: prd:lau, ns:lau, rel:lau-case-backend-pr-532

#534 LAU-744 bump flyway
  build.gradle
Labels: prd:lau, ns:lau, rel:lau-case-backend-pr-534

#535 Revert "LAU-744 bump flyway"
  build.gradle
Labels: prd:lau, ns:lau, rel:lau-case-backend-pr-535

#536 LAU-744 revert flyway upgrade
  .github/renovate.json
  build.gradle
  charts/lau-case-backend/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/laubackend/cases/config/FlywayCustomConfig.java
Labels: prd:lau, ns:lau, rel:lau-case-backend-pr-536
